project:
  type: website
  output-dir: docs

website:
  title: "Rain Luciano"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - resume.qmd
      - posts.qmd
format:
  html:
    theme: sandstone
    css: styles.css
    toc: true



