project:
  type: website
  output-dir: docs

website:
  title: "Rain Luciano"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - CV.qmd
format:
  html:
    theme: Zephyr
    css: styles.css
    toc: true



